# Generated by Django 5.0.8 on 2026-07-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('refeicoes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisefeedback',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_feedback', to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='usuarios.aluno'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='refeicoes.refeicao'),
        ),
        migrations.AddField(
            model_name='analisefeedback',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='feedbacks.feedback'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['criado_em'], name='feedback_criado__a8ff7e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['nota'], name='feedback_nota_f838af_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('aluno', 'refeicao'), name='uk_feedback_aluno_refeicao'),
        ),
        migrations.AddIndex(
            model_name='analisefeedback',
            index=models.Index(fields=['status_analise'], name='analise_fee_status__e88695_idx'),
        ),
        migrations.AddIndex(
            model_name='analisefeedback',
            index=models.Index(fields=['visualizado_em'], name='analise_fee_visuali_ef47b4_idx'),
        ),
    ]
