# Generated by Django 5.0.8 on 2026-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('PRATO_PRINCIPAL', 'Prato principal'), ('ACOMPANHAMENTO', 'Acompanhamento'), ('SALADA', 'Salada'), ('BEBIDA', 'Bebida')], max_length=30)),
                ('nome', models.CharField(max_length=150)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'item da refeição',
                'verbose_name_plural': 'itens da refeição',
                'db_table': 'item_refeicao',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Almoço'), ('J', 'Jantar'), ('L', 'Lanche')], max_length=1)),
                ('data_refeicao', models.DateField()),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('V', 'Vespertino'), ('N', 'Noturno')], max_length=1)),
                ('campus', models.CharField(default='IFRN Campus Canguaretama', max_length=150)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado'), ('ENCERRADA', 'Encerrada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'refeição',
                'verbose_name_plural': 'refeições',
                'db_table': 'refeicao',
                'ordering': ['-data_refeicao', 'tipo'],
            },
        ),
    ]
