# Generated by Django 5.0.8 on 2026-07-05 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refeicoes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicao',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refeicoes_cadastradas', to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='itemrefeicao',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='refeicoes.refeicao'),
        ),
        migrations.AddIndex(
            model_name='refeicao',
            index=models.Index(fields=['data_refeicao'], name='refeicao_data_re_92dee1_idx'),
        ),
        migrations.AddIndex(
            model_name='refeicao',
            index=models.Index(fields=['tipo'], name='refeicao_tipo_f908df_idx'),
        ),
        migrations.AddIndex(
            model_name='refeicao',
            index=models.Index(fields=['turno'], name='refeicao_turno_3a14af_idx'),
        ),
        migrations.AddIndex(
            model_name='refeicao',
            index=models.Index(fields=['status'], name='refeicao_status_ccb942_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemrefeicao',
            constraint=models.UniqueConstraint(fields=('refeicao', 'tipo_item', 'nome'), name='uk_item_refeicao_nome'),
        ),
    ]
